name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: login docker hub
      uses: docker/login-action@v1
      with:
       username: $ {{secrets.DOCKER_HUB_USERNAME}}
       password: $ {{secrets.DOCKER_HUB_TOKEN}}
      
    - name: build and push docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: johannneumann72/productservice:latest
      
